### ISSUE TITLE
Create proper readme and work on database schema.

### ISSUE THREAD

**Issue by Schluucht** [Schluucht/Destiny#13]

**Comment by lucgiffon** [comment]
If we follow sphinx conventions for documenting functions, we can use it to make an automatic documentation

**Comment by Schluucht** [comment]
Don't understand your last comment @lucgiffon .

Destiny project won't be a big project . So wedon't need  wiki pages. Any information about project will go in README.

**Comment by lucgiffon** [comment]
http://www.sphinx-doc.org/en/stable/

Sphinx is a documentation generator. It is very powerfull and if we add proper docstring in our code it will generate the wiki alone with very little man-craft. Thats all, the first step in order to have a wiki is to have good docstring in our code. A good ressource for writing good documentation: https://www.python.org/dev/peps/pep-0258/

**Comment by Schluucht** [comment]
Fixes in #35 .
